### ISSUE TITLE
Something about network?

### ISSUE THREAD

**Issue by GuideWsp** [qibao77/CFSNet#3]
In the paper, on the first three FC :512 x 256, 256x128, 128x64.
but the \alpha_in is a scalar. Do you set as this:
tensorIN = torch.ones(N, 512) * \alpha_in?

Hope your answer! Thanks.

**Comment by qibao77** [comment]
Thank you for your attention. Yes, we put torch.ones(N, 512) * \alpha_in into the network.

**Comment by GuideWsp** [comment]
Thanks!
